### ISSUE TITLE
[DOC] Many links are outdated

### ISSUE THREAD

**Issue by SashoStoichkov** [nhcarrigan/notes#41]
# Incorrect Documentation

## Describe the error

Every link that is redirecting to `notes/blob/main/<folder-name>` is broken since all the "notes" are in `docs` folder.

## How to fix

Example:
```diff
- https://github.com/nhcarrigan/notes/blob/main/transfer-labels/export.md
+ https://github.com/nhcarrigan/notes/blob/main/docs/transfer-labels/export.md
```

**Comment by nhcarrigan** [comment]
If you're referring to the links in the actual docs files, those are all relative links designed to work in the rendered website 🙂

**Comment by SashoStoichkov** [comment]
When I hover over the link [here](https://github.com/nhcarrigan/notes/blob/main/docs/transfer-labels/index.md) (*I hope that it's visible in the screenshot*)

![Screenshot_20210719_172827](https://user-images.githubusercontent.com/24972335/126176486-9c477e02-e641-4ef1-9814-59c7c94fb5fa.png)

... and I click it - this 👇🏻 is what I get

![Screenshot_20210719_172855](https://user-images.githubusercontent.com/24972335/126176574-86d75512-e5b1-46be-924a-f0665aa3ff1c.png)

**Comment by nhcarrigan** [comment]
Right because those links aren't meant to work in GitHub, they're meant to work on https://www.nhcarrigan.com/notes

**Comment by SashoStoichkov** [comment]
Ohhhhh okay - sorry about that then
