### ISSUE TITLE
[DOC] - Update actions/setup-node version

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/notes#74]
### What is incorrect in the documentation?

`actions/setup-node` received a version update, and needs to be changed in the action templates here.

### What should that text say?

In the following files:

- https://github.com/nhcarrigan/notes/blob/main/docs/github-workflows/angular-deploy.md
- https://github.com/nhcarrigan/notes/blob/main/docs/github-workflows/codeql-ts-node.md
- https://github.com/nhcarrigan/notes/blob/main/docs/github-workflows/node-ci-ts.md

update the `actions/setup-node@v2` line to `actions/setup-node@v3`.

**Comment by sauradip007** [comment]
I would like to take it up, shall I update actions/checkout to node@v3 as well?

**Comment by nhcarrigan** [comment]
`actions/checkout` is a separate package which is still on v2.4.0.

**Comment by sauradip007** [comment]
https://github.com/nhcarrigan/notes/pull/75
