### ISSUE TITLE
[BUG] - Link not working

### ISSUE THREAD

**Issue by schmelto** [nhcarrigan/notes#81]
### What bug did you encounter?

https://www.nhcarrigan.com/notes/#/funny-codes/index
The `View Code`-Link is not working.
Redirects to : https://www.nhcarrigan.com/notes/#/./hello-world

### What did you expect to happen?

Should be direct to : https://www.nhcarrigan.com/notes/#/funny-codes/hello-world

**Comment by nhcarrigan** [comment]
Thanks for catching this! Going to open up for first time contributors. A PR which resolves this issue will:

- Within the https://github.com/nhcarrigan/notes/blob/main/docs/funny-codes/index.md file:
  - Update the link from `./hello-world.md` to `funny-codes/hello-world.md`.
