### ISSUE TITLE
[BUG] - 404 Not found (Let's Encrypt notes)

### ISSUE THREAD

**Issue by jaas666** [nhcarrigan/notes#90]
### What bug did you encounter?

https://www.nhcarrigan.com/notes/#/general/lets-encrypt goes to a 404 (not found) error

### What did you expect to happen?

The page to load

### Screenshots

![Screenshot_20220420-105027_Chrome](https://user-images.githubusercontent.com/30204147/164271581-f8955d9a-d59f-4c83-8cdb-1b05e871c930.png)

**Comment by nhcarrigan** [comment]
Hey there,

Where did you find this link?

**Comment by nhcarrigan** [comment]
Going to close this as it will be resolved in the above mentioned issue.
