### ISSUE TITLE
[BUG] - 404 not found (Digital Ocean notes)

### ISSUE THREAD

**Issue by jaas666** [nhcarrigan/notes#91]
### What bug did you encounter?

https://www.nhcarrigan.com/notes/#/notes/do-droplet-setup

404 not found

### What did you expect to happen?

Page to load

**Comment by nhcarrigan** [comment]
Hey there,

Where did you find this link?

**Comment by nhcarrigan** [comment]
Going to close this as it will be resolved in the above mentioned issue.

**Comment by jaas666** [comment]
[General notes](https://www.nhcarrigan.com/notes/#/general/index)

The note shows up on the page content but links to them are missing from the left navigation.

Maybe the intention was to remove them altogether and forgot to remove the page?
